
class ButtonMaps {

    buttonTextMap: { [key: string]: string } = {
        key_1: '1',
        key_2: '2',
        key_3: '3',
        key_4: '4',
        key_5: '5',
        key_6: '6',
        key_7: '7',
        key_8: '8',
        key_9: '9',
        key_0: '0',
        key_q: 'q',
        key_w: 'w',
        key_e: 'e',
        key_r: 'r',
        key_t: 't',
        key_y: 'y',
        key_u: 'u',
        key_i: 'i',
        key_o: 'o',
        key_p: 'p',
        key_a: 'a',
        key_s: 's',
        key_d: 'd',
        key_f: 'f',
        key_g: 'g',
        key_h: 'h',
        key_j: 'j',
        key_k: 'k',
        key_l: 'l',
        key_z: 'z',
        key_x: 'x',
        key_c: 'c',
        key_v: 'v',
        key_b: 'b',
        key_n: 'n',
        key_m: 'm',
        key_space: ' ',
        key_semicolon: ';',
        key_uppercomma: "'",
        key_sq_bracket_left: '[',
        key_sq_bracket_right: ']',
        key_comma: ',',
        key_slash: '\\',
        key_revslash: '/',
        key_dot: '.',
        key_minus: '-',
        key_plus: '+'
    };

    buttonTextMapRus: { [key: string]: string } = {
        key_1: '1',
        key_2: '2',
        key_3: '3',
        key_4: '4',
        key_5: '5',
        key_6: '6',
        key_7: '7',
        key_8: '8',
        key_9: '9',
        key_0: '0',
        key_q: 'й',
        key_w: 'ц',
        key_e: 'у',
        key_r: 'к',
        key_t: 'е',
        key_y: 'н',
        key_u: 'г',
        key_i: 'ш',
        key_o: 'щ',
        key_p: 'з',
        key_a: 'ф',
        key_s: 'ы',
        key_d: 'в',
        key_f: 'а',
        key_g: 'п',
        key_h: 'р',
        key_j: 'о',
        key_k: 'л',
        key_l: 'д',
        key_z: 'я',
        key_x: 'ч',
        key_c: 'с',
        key_v: 'м',
        key_b: 'и',
        key_n: 'т',
        key_m: 'ь',
        key_space: ' ',
        key_semicolon: 'ж',
        key_uppercomma: "э",
        key_sq_bracket_left: 'х',
        key_sq_bracket_right: 'ъ',
        key_comma: 'б',
        key_slash: '\\',
        key_revslash: '/',
        key_dot: 'ю',
        key_minus: '-',
        key_plus: '+'
    };

};

export { ButtonMaps };